export default {
  Abdomen: 'ABDOMEN',
  'Abdomen and Pelvis': 'ABDOMENPELVIS',
  'Adrenal gland': 'ADRENAL',
  'Ankle joint': 'ANKLE',
  Aorta: 'AORTA',
  Axilla: 'AXILLA',
  Back: 'BACK',
  Bladder: 'BLADDER',
  Brain: 'BRAIN',
  Breast: 'BREAST',
  Bronchus: 'BRONCHUS',
  Buttock: 'BUTTOCK',
  Calcaneus: 'CALCANEUS',
  'Calf of leg': 'CALF',
  'Carotid Artery': 'CAROTID',
  Cerebellum: 'CEREBELLUM',
  'Cervical spine': 'CSPINE',
  'Cervico-thoracic spine': 'CTSPINE',
  Cervix: 'CERVIX',
  Cheek: 'CHEEK',
  Chest: 'CHEST',
  'Chest, Abdomen and Pelvis': 'CHESTABDPELVIS',
  'Chest and Abdomen': 'CHESTABDOMEN',
  'Circle of Willis': 'CIRCLEOFWILLIS',
  Clavicle: 'CLAVICLE',
  Coccyx: 'COCCYX',
  Colon: 'COLON',
  Cornea: 'CORNEA',
  'Coronary artery': 'CORONARYARTERY',
  Duodenum: 'DUODENUM',
  Ear: 'EAR',
  'Elbow joint': 'ELBOW',
  'Entire body': 'WHOLEBODY',
  Esophagus: 'ESOPHAGUS',
  Extremity: 'EXTREMITY',
  Eye: 'EYE',
  Eyelid: 'EYELID',
  Face: 'FACE',
  Femur: 'FEMUR',
  Finger: 'FINGER',
  Foot: 'FOOT',
  Gallbladder: 'GALLBLADDER',
  Hand: 'HAND',
  Head: 'HEAD',
  'Head and Neck': 'HEADNECK',
  Heart: 'HEART',
  'Hip joint': 'HIP',
  Humerus: 'HUMERUS',
  Ileum: 'ILEUM',
  Ilium: 'ILIUM',
  'Internal Auditory Canal': 'IAC',
  'Jaw region': 'JAW',
  Jejunum: 'JEJUNUM',
  Kidney: 'KIDNEY',
  Knee: 'KNEE',
  Larynx: 'LARYNX',
  Liver: 'LIVER',
  'Lower leg': 'LEG',
  'Lumbar spine': 'LSPINE',
  'Lumbo-sacral spine': 'LSSPINE',
  Lung: 'LUNG',
  Mandible: 'JAW',
  Maxilla: 'MAXILLA',
  Mediastinum: 'MEDIASTINUM',
  Mouth: 'MOUTH',
  Neck: 'NECK',
  'Neck, Chest, Abdomen and Pelvis': 'NECKCHESTABDPELV',
  'Neck, Chest and Abdomen': 'NECKCHESTABDOMEN',
  'Neck and Chest': 'NECKCHEST',
  Nose: 'NOSE',
  'Orbital structure': 'ORBIT',
  Ovary: 'OVARY',
  Pancreas: 'PANCREAS',
  'Parotid gland': 'PAROTID',
  Patella: 'PATELLA',
  Pelvis: 'PELVIS',
  Penis: 'PENIS',
  Pharynx: 'PHARYNX',
  Prostate: 'PROSTATE',
  Radius: 'RADIUS',
  'Radius and ulna': 'RADIUSULNA',
  Rectum: 'RECTUM',
  Rib: 'RIB',
  Sacrum: 'SSPINE',
  Scalp: 'SCALP',
  Scapula: 'SCAPULA',
  Sclera: 'SCLERA',
  Scrotum: 'SCROTUM',
  Shoulder: 'SHOULDER',
  Skull: 'SKULL',
  Spine: 'SPINE',
  Spleen: 'SPLEEN',
  Sternum: 'STERNUM',
  Stomach: 'STOMACH',
  'Submandibular gland': 'SUBMANDIBULAR',
  'Temporomandibular joint': 'TMJ',
  Testis: 'TESTIS',
  Thigh: 'THIGH',
  'Thoracic spine': 'TSPINE',
  'Thoraco-lumbar spine': 'TLSPINE',
  Thumb: 'THUMB',
  Thymus: 'THYMUS',
  Thyroid: 'THYROID',
  Tibia: 'TIBIA',
  'Tibia and fibula': 'TIBIAFIBULA',
  Toe: 'TOE',
  Tongue: 'TONGUE',
  Trachea: 'TRACHEA',
  Ulna: 'ULNA',
  'Upper arm': 'ARM',
  Ureter: 'URETER',
  Urethra: 'URETHRA',
  Uterus: 'UTERUS',
  Vagina: 'VAGINA',
  Vulva: 'VULVA',
  'Wrist joint': 'WRIST',
  Zygoma: 'ZYGOMA',
};
