export default [
  'AR - Autorefraction',
  'BDUS - Bone Densitometry (ultrasound)',
  'BI - Biomagnetic imaging',
  'BMD - Bone Densitometry (X-Ray)',
  'CR - Computed Radiography',
  'CT - Computed Tomography',
  'DG - Diaphanography',
  'DX - Digital Radiography',
  'ECG - Electrocardiography',
  'EPS - Cardiac Electrophysiology',
  'ES - Endoscopy',
  'FID - Fiducials',
  'GM - General Microscopy',
  'HD - Hemodynamic Waveform',
  'IO - Intra-Oral Radiography',
  'IOL - Intraocular Lens Data',
  'IVOCT - Intravascular Optical Coherence Tomography',
  'IVUS - Intravascular Ultrasound',
  'KER - Keratometry',
  'LEN - Lensometry',
  'LS - Laser surface scan',
  'MG - Mammography',
  'MR - Magnetic Resonance',
  'M3D - Model for 3D Manufacturing',
  'NM - Nuclear Medicine',
  'OAM - Ophthalmic Axial Measurements',
  'OCT - Optical Coherence Tomography (non-Ophthalmic)',
  'OP - Ophthalmic Photography',
  'OPM - Ophthalmic Mapping',
  'OPT - Ophthalmic Tomography',
  'OPTBSV - Ophthalmic Tomography B-scan Volume Analysis',
  'OPTENF - Ophthalmic Tomography En Face',
  'OPV - Ophthalmic Visual Field',
  'OSS - Optical Surface Scan',
  'OT - Other',
  'PT - Positron emission tomography (PET)',
  'PX - Panoramic X-Ray',
  'REG - Registration',
  'RESP - Respiratory Waveform',
  'RF - Radio Fluoroscopy',
  'RG - Radiographic imaging (conventional film/screen)',
  'RTIMAGE - Radiotherapy Image',
  'RTRAD - RT Radiation',
  'SEG - Segmentation',
  'SM - Slide Microscopy',
  'SMR - Stereometric Relationship',
  'SRF - Subjective Refraction',
  'STAIN - Automated Slide Stainer',
  'TG - Thermography',
  'US - Ultrasound',
  'VA - Visual Acuity',
  'XA - X-Ray Angiography',
  'XC - External-camera Photography',
];
